In [1]:
#2D Array
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [2]:
#3D Array
import numpy as np
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [3]:
import array as numpy

a = np.array(42)
b = np.array([1,2,3,4,5])
c = np.array([[1,2,3],[4,5,6]])
d = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [4]:
#Access array element
import numpy as np
arr = np.array([1,2,3,4])
print(arr[1])

import numpy as np
arr = np.array([1,2,3,4])
print(arr[0])

2
1


In [5]:
#Access 2D Arrays
import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print('2nd element on 1st row: ', arr[0,1])

2nd element on 1st row:  2


In [6]:
#Removing the elements from index 1 to 5

import numpy as np
arr = np.array([1,2,3,4,5,6,7])
print(arr[1:5])

[2 3 4 5]


In [9]:
#Start index has not been mentioned if we don't pass start its considered 0
import numpy as np
arr = np.array([1,2,3,4,5,6,7])
print(arr[:5])
      #where index has not been mentioned

[1 2 3 4 5]


In [10]:
#Start and end index both are not mentioned

import numpy as np
arr = np.array([1,2,3,4,5,6,7])
print(arr[:]) #where start and end both are not mentioned

[1 2 3 4 5 6 7]


In [12]:
#Slice elements from index 4 to end of the array:

import numpy as np
arr = np.array([1,2,3,4,5,6,7])
print(arr[4:])

[5 6 7]


In [13]:
#Negative Slicing

import numpy as np
arr = np.array([1,2,3,4,5,6,7])
print(arr[-3:-1])

[5 6]


In [15]:
#Using step value to determine the step of slicing

import numpy as np
arr = np.array([1,2,3,4,5,6,7])
print(arr[1:5:2])

[2 4]


In [17]:
#Return every other element from the entire array

import numpy as np
arr = np.array([1,2,3,4,5,6,7])
print(arr[::2])

[1 3 5 7]
